<a href="https://colab.research.google.com/github/Alotrpyco/Alotrpyco/blob/main/Curso_IFMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Biblioteca Numpy: Conceitos e Uso**
 **Numpy** é uma biblioteca matemática pra o python. Ele nos permite fazer computação de forma eficiente e eficaz. É melhor do que python regular por causa de suas incríveis capacidades.

 Um array em python é uma estrutura de dados que permite armazenar uma coleção de intens em uma única variável. os intens podem ser de qualquer tipo, como números, strings ou até mesmo outros arrays. Em python, os arrays são geralmente implementados como listas. I "numpy" fornece uma implementação mais avançada de arrays.

#Importando a Biblioteca

In [4]:
import numpy as np

#array python e um array np

Os arrays np são melhores em termos de computação mais rápida e facilidade de manipulação.

Array tradicional em Python

In [2]:
arr = [1, 2, 3, 4]
print(arr)
print(arr[0])

[1, 2, 3, 4]
1


Array utilizado Numpy

In [5]:
arr2 = np.array([1, 2, 3, 4])
print(arr2)
print(arr2[0])

[1 2 3 4]
1


#np.arange()
É uma função presente na biblioteca numpy que gera um array contendo uma progressão aritimética de números.

In [12]:
arr = np.arange(0, 100, 1,  'int')
print (arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#reshape()
É uma função presente na biblioteca numpy que modifica a forma de um array existente sem alterar seus dados.


In [ ]:
#: O array que deseja ser modificado.
#newsshape: A nova forma do array. Isso pode ser especificado como uma tupla de inteiros ou como uma lista de inteiros.
np.reshape(a, newshape, order = 'C')

In [13]:
arr = np.reshape(arr, (10,10))
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#indexação de matriz (tensores)
A indexação de matrizes em numpy é semelhante á indexação de listas em Python. Você pode usar colchetes [] para acessar elementos em uma matriz.

A indexação de uma matriz numpy 2D é feita com base nas linhas e colnas

matriz[linha,coluna]

In [16]:
arr[8,5]

np.int64(85)

#Operações sobre matrizes (tensores)

A biblioteca numpy fornece uma série de operações matemáticas para trablhar com matrizes, incluindo adição, sibtração, multiplicação, divisão, etc.




In [ ]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5,6], [7,8]])

matriz_soma = matriz1 + matriz2
print(matriz_soma)


#np.sum()